### ISSUE TITLE
When is wrapper.setProps + setTimeout needed?

### ISSUE THREAD

**Issue by oskarhane** [windyGex/preact-compat-enzyme#2]
Hi,
Thanks for this package!

I don't understand when I need to use `setProps` (and therefore make assertions wrapped in `setTimeout`).

The following code does not work, children is always empty:

```
const wrapper = mount(<Render if={false}><span>Hello</span></Render>)
```

This is needed:

```
    const wrapper = mount(<Render />)
    wrapper.setProps({if: false, children: <span>Hello</span>})
```

Could you help me understand why?

**Comment by windyGex** [comment]
Maybe this is caused by [preact](https://github.com/developit/preact/blob/master/src/render-queue.js#L10). I'm not sure. And please give me a real code to debug it.

**Comment by oskarhane** [comment]
Thanks for the fast response!

You can clone `git@github.com:oskarhane/neo4j-browser.git` and checkout the `3.0-bring-back-enzyme` branch and run `yarn install` and then `yarn dev` to test in watch mode.


The relevant test is in https://github.com/oskarhane/neo4j-browser/blob/45654bfcfc46055d7a7f8a21e63d6bfecbd007a5/src/browser/components/Render/index.test.js#L29-L56

**Comment by windyGex** [comment]
![image](https://cloud.githubusercontent.com/assets/197348/26671907/bd5ab85c-46e9-11e7-9e94-08a3849b48fe.png)
Sorry, I got a error when running `yarn dev`

**Comment by oskarhane** [comment]
Weird. What if you try `npm run dev`?
You installed the dependecies?

Do you have a global old version of jest installed?

**Comment by windyGex** [comment]
Try `npm run dev` got the same result. I have installed dependencies using `yarn install`. I'm not sure it related to node version. My node version is 6.4.0.

**Comment by mparpaillon** [comment]
Hi. Thanks for this

I have the same problem. Any news about this ?

**Comment by oskarhane** [comment]
I've found that `wrapper.update()` after `wrapper.update.setProps` removes the need for async assertions.
Does that work for you too @mparpaillon?

**Comment by mparpaillon** [comment]
@oskarhane Yes. Just a typo in your solution. It's

```js
wrapper.setProps({bla: 'blabla'});
wrapper.update();
```

Thanks a lot :)

**Comment by mparpaillon** [comment]
@windyGex This can be closed I guess

**Comment by oskarhane** [comment]
Sorry, typing on the phone :)
